server:
  port: 9001
  servlet:
    context-path: /
spring:
  application:
    name: cloud-payment-service # 服务名称
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver # Oracle数据库驱动包
    url: jdbc:oracle:thin:@localhost:1521/ORCL
    username: C##testdb
    password: C##testdb