server:
  port: 9001
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #driverClassName: oracle.jdbc.OracleDriver
    username: C##testdb
    password: C##testdb